---
- name: Install Nginx
  hosts: localhost
  become: yes
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    
    - name: Install Nginx
      apt:
        name: nginx
        state: present

- name: Get Nginx Status
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Get Nginx Status
      command: systemctl status nginx
      register: nginx_status

    - name: Write Nginx Status to File
      copy:
        content: "{{ nginx_status.stdout_lines | join('\\n') }}"
        dest: /tmp/nginx_status.txt